### ISSUE TITLE
Add 'external' href link style

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#110]
Similar to the [`.readmore` link style](https://github.com/ebiwd/EBI-Framework/blob/v1.2/css/ebi-global.scss#L921) it would be useful to have an `.external` link style for `target="_blank"` links. 

We can use the EBI Icon Font: 
- '<* class="icon icon-generic" data-icon="x">'
- `font-family: 'EBI-Generic';`
- `content: " x";`

Sass code (includes some tweaks from testing):
``` css
a.external{
  &:after {
    content: " x";
    font-family: "EBI-Generic";
    font-size: .65rem;
    position: relative;
    top: -1px;
    margin-left: .4rem;
  }
}
```

Usage:
``` html
<a href="//somedomain.com" class="external">Link</a>
```

Four tasks:
- ~Add to v1.1~ (won't plan to add to v1.1 as this is not intended to get "new" things)
- [x] Add to v1.2
- [x] Add to v1.3
- [x] Document pattern in EBI Style Lab at https://www.ebi.ac.uk/style-lab/websites/patterns/formatting.html

Bonus:
- [x] JS Boilerplate in `ebiFoundationExtend` to automatically add `.external` and `target="_blank"` external to links in `div#content`
