### ISSUE TITLE
Set the font-size using an utility class

### ISSUE THREAD

**Issue by Kerruba** [ebiwd/EBI-Framework#113]
Hello, 

I would find it very useful to use an utility class to tweak the font-size of an element. Specifically if that element is an Icon created with a font, being able to set the size of that using a class like `size-50` to resize it to 50% can be useful.

**Comment by khawkins98** [comment]
I think this could be quite useful to scale things down and up.

Could do:
```css
@for $i from 0 through 50
  .size-#{$i}0
    size: #{$i}0%
```

to get
```css
.size-00 {
  size: 00%;
}

.size-10 {
  size: 10%;
}

.size-20 {
  size: 20%;
}

.size-30 {
  size: 30%;
}

.size-40 {
  size: 40%;
}

.size-50 {
  size: 50%;
}

.size-60 {
  size: 60%;
}

.size-70 {
  size: 70%;
}

.size-80 {
  size: 80%;
}

.size-90 {
  size: 90%;
}

.size-100 {
  size: 100%;
}

.size-110 {
  size: 110%;
}

.size-120 {
  size: 120%;
}

.size-130 {
  size: 130%;
}

.size-140 {
  size: 140%;
}

.size-150 {
  size: 150%;
}

.size-160 {
  size: 160%;
}

.size-170 {
  size: 170%;
}

.size-180 {
  size: 180%;
}

.size-190 {
  size: 190%;
}

.size-200 {
  size: 200%;
}

.size-210 {
  size: 210%;
}

.size-220 {
  size: 220%;
}

.size-230 {
  size: 230%;
}

.size-240 {
  size: 240%;
}

.size-250 {
  size: 250%;
}

.size-260 {
  size: 260%;
}

.size-270 {
  size: 270%;
}

.size-280 {
  size: 280%;
}

.size-290 {
  size: 290%;
}

.size-300 {
  size: 300%;
}

.size-310 {
  size: 310%;
}

.size-320 {
  size: 320%;
}

.size-330 {
  size: 330%;
}

.size-340 {
  size: 340%;
}

.size-350 {
  size: 350%;
}

.size-360 {
  size: 360%;
}

.size-370 {
  size: 370%;
}

.size-380 {
  size: 380%;
}

.size-390 {
  size: 390%;
}

.size-400 {
  size: 400%;
}

.size-410 {
  size: 410%;
}

.size-420 {
  size: 420%;
}

.size-430 {
  size: 430%;
}

.size-440 {
  size: 440%;
}

.size-450 {
  size: 450%;
}

.size-460 {
  size: 460%;
}

.size-470 {
  size: 470%;
}

.size-480 {
  size: 480%;
}

.size-490 {
  size: 490%;
}

.size-500 {
  size: 500%;
}
```

**Comment by Kerruba** [comment]
I think it would work but maybe is too granular? 
If you need something more specific it would be probably  easier to define a more specific class I'd think

What about 25% step increment?

**Comment by khawkins98** [comment]
Yeah, seems reasonable. Could do:

```css
@for $i from 0 through 20 {
  .size-#{$i*25} { size: 25%*$i; }
}
```

To get
```css
.size-0 {
  size: 0%;
}

.size-25 {
  size: 25%;
}

.size-50 {
  size: 50%;
}

.size-75 {
  size: 75%;
}

.size-100 {
  size: 100%;
}

.size-125 {
  size: 125%;
}

.size-150 {
  size: 150%;
}

.size-175 {
  size: 175%;
}

.size-200 {
  size: 200%;
}

.size-225 {
  size: 225%;
}

.size-250 {
  size: 250%;
}

.size-275 {
  size: 275%;
}

.size-300 {
  size: 300%;
}

.size-325 {
  size: 325%;
}

.size-350 {
  size: 350%;
}

.size-375 {
  size: 375%;
}

.size-400 {
  size: 400%;
}

.size-425 {
  size: 425%;
}

.size-450 {
  size: 450%;
}

.size-475 {
  size: 475%;
}

.size-500 {
  size: 500%;
}

```
