### ISSUE TITLE
Page movement on search icon and EMBL-EBI logo mouseover

### ISSUE THREAD

**Issue by mandarsd** [ebiwd/EBI-Framework#141]
It looks like top margin is getting applied on mouseover.

**Comment by mandarsd** [comment]
Yes! this one. It looks like a glitch to me because the entire page moves down. 
I liked the idea behind the slide out. It would be nice if the sliding bit happens with 'absolute' position so the entire page won't move.

**Comment by khawkins98** [comment]
It's actually not a position trick, but rather there's a 4px white border that's being animated in and out. 

We could work around the "push down"  by adding to the existing:
``` css
.masthead-black-bar {
  margin-bottom: 0;
  position: relative;
  z-index: 10;
}

.masthead-black-bar.peek {
    margin-bottom: -4px;
}
```

Here's what that looks like in Chrome (of course also need to check in other browsers).

![kapture 2018-08-01 at 9 00 30](https://user-images.githubusercontent.com/928100/43506119-63b3da16-9569-11e8-81ea-f5a5b1cfea2a.gif)
