### ISSUE TITLE
Better supporting data-oriented tables

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#65]
Roman Laskowski (Thornton research group) is working to port VarSt and has [encountered some use cases](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=175905) whose solutions will likely be of use to others:

1. How to make tables not 100% wide
2. Thinner padding on data tables
3. Stretch images out of their normal aspect ratio

These aren't surprising issues for data-oriented tables.

Spirit of solution is to create individual overrides for the above (not change default behaviour) and to create a new style for `table.data-table` that would implement this more compact look and is a placeholder for further functionality/tweaks to be added.

**Comment by khawkins98** [comment]
New tooling allows for users to:
- specify td padding `.padding-none` `.padding-small`
- disable 100% width `.width-auto`
- align text to top `.align-top`
- small text (already possible) `.small`

The code:
``` css
/* Data table solutions */
/* Tables with custom padding */
table .padding-none th,
table .padding-none td
table.padding-none tbody th,
table.padding-none tbody td {
  padding: 0;
}
table .padding-small th,
table .padding-small td
table.padding-small tbody th,
table.padding-small tbody td,
table.data-table tbody th,
table.data-table tbody td {
  padding: 0rem 0.2rem 0.2rem;
}
/* None 100% wide tables */
table.data-table,
table.width-auto { width: auto; }
/* some images should be stretched, such as sparkline-style gifs */
table.data-table img,
img.stretch { height: inherit; }
/* align table cell text to top */
table.data-table td,
table.align-top td,
table td.align-top {
  vertical-align: top;
}

```
