### ISSUE TITLE
Add visibile a:focus style

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#99]
Using an obvious focus state would be good for accessibility / tab navigation; like so:

![image](https://user-images.githubusercontent.com/928100/28667965-ba146d48-72c5-11e7-949b-9ac5555f4054.png)

```css
a:focus {
    outline: 3px solid #767676;
}
```
